# uses xcodebuild and xcpretty to test Swift snapshots

os:
- osx
sudo: required
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
before_install:
- gem install xcpretty
script:
  - set -o pipefail
  - xcodebuild test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -project AES256CBC.xcodeproj -scheme "AES256CBC (iOS)" -destination name="iPhone 6" | xcpretty -c
